# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13d91acfb957dbdf674e2fc24ce6831e119820ced2069ffb66e3cdf7ec462bd8861559738d5ca8354cd5f7541914b9044f0b7bf268f3a1c6116d5329ea9c3874

test:
  secret_key_base: 0255a694992a23f6746187efa9cb01ec00d591f48e233c5f1bed0fafbc5f085e0f88752ee49da65c5a2dde7d08509583eaf3d40510e5ccda92ef61187cbe2333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
